"""Fix DB-wide nullability drift (Nebenfund aus G.3.6)

Revision ID: 0019
Revises: 0018
Create Date: 2026-08-28

`alembic check` zeigte seit der G.3.6-Session (Diary-Feature) eine
umfangreiche Drift: viele Spalten sind in den Modellen als NOT NULL
deklariert (nicht-optionaler Mapped-Typ, Python-seitiger default= oder
server_default=func.now()), aber in der echten DB weiterhin nullable -
die urspruenglichen Migrationen haben nie explizit nullable=False
gesetzt. Vor dieser Migration live geprueft: keine der 30 betroffenen
Spalten hat aktuell einen einzigen NULL-Wert in der Produktions-DB,
das Nachziehen ist also gefahrlos.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "0019"
down_revision = "0018"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applications', 'job_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('applications', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('applications', 'kanban_position',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('applications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('applications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('backup_logs', 'erstellt_am',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('backup_logs', 'erfolgreich',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('blocklist', 'erstellt_am',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('cover_letter_templates', 'placeholders',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('cover_letters', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('cv_data', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('history', 'event_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('history', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('jobs', 'is_hidden',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('jobs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('reminders', 'is_done',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('reminders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('settings', 'theme',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('settings', 'language',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)
    op.alter_column('settings', 'ai_model',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('settings', 'ai_tone',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('settings', 'default_radius_km',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('settings', 'hide_ausbildung',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('settings', 'reminder_default_days',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('text_snippets', 'category',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'allgemein'::character varying"))
    op.alter_column('text_snippets', 'is_custom',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('text_snippets', 'sprache',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'de'::character varying"))
    op.alter_column('text_snippets', 'erstellt_am',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_badges', 'badge_key',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_badges', 'freigeschaltet_am',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_badges', 'freigeschaltet_am',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_badges', 'badge_key',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('text_snippets', 'erstellt_am',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('text_snippets', 'sprache',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'de'::character varying"))
    op.alter_column('text_snippets', 'is_custom',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('text_snippets', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'allgemein'::character varying"))
    op.alter_column('settings', 'reminder_default_days',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('settings', 'hide_ausbildung',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('settings', 'default_radius_km',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('settings', 'ai_tone',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('settings', 'ai_model',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('settings', 'language',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
    op.alter_column('settings', 'theme',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('reminders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('reminders', 'is_done',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('jobs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('jobs', 'is_hidden',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('history', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('history', 'event_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('cv_data', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('cover_letters', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('cover_letter_templates', 'placeholders',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('blocklist', 'erstellt_am',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('backup_logs', 'erfolgreich',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('backup_logs', 'erstellt_am',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('applications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('applications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('applications', 'kanban_position',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('applications', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('applications', 'job_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
